max_epochs: 15
gpus: "2"
monitor_metric: "val_accuracy" # val_accuracy
monitor_mode: "max"
checkpoint_filename: "best-checkpoint-{epoch}-{val_accuracy:.2f}"
save_top_k: 1
log_every_n_steps: 5

early_stopping:
  monitor_metric: "val_accuracy"  # Same metric as above
  mode: "max"                           # "max" for accuracy, "min" for loss
  patience: 5                           # Stop training after 5 epochs with no improvement